name: Release
on:
  release:
    types: [created]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Update version
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: "gradle.properties"
          property: "mod_version"
          value: ${{ github.event.release.tag_name }}

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build and upload
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build modrinth publish
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG: ${{ github.event.release.body }}
